### ISSUE TITLE
a more detailed tutorial

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [JYC333/Anki-Sync-to-Obsidian#1]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/71814666/222088260-e45cf6cb-f40b-4ddf-9178-da3f8693cb8b.png">
I hope there will be a more detailed tutorial on how to configure it, thank you.

**Comment by shoudeyunkaijianyueming** [comment]
Where should it be configured，the absolute path of your Obsidian vault.

**Comment by shoudeyunkaijianyueming** [comment]
thanks

**Comment by JYC333** [comment]
Sorry for the late reply, I think it can be easily found in the plugin settings.

Go from Tools -> Add-ons -> click on "Sync to Obsidian" -> Click "Config" on the right -> Put the absolute path of your Obsidan vault in the obsidianPath field.

**Comment by shoudeyunkaijianyueming** [comment]
How should mac fill it in? I found that there was an error after filling it out.

**Comment by shoudeyunkaijianyueming** [comment]
/Users/XX/Documents/同步空间/笔记ob/ob法律笔记
这是我输入的

**Comment by JYC333** [comment]
这个我确实不是很清楚了，我目前没有 mac 可以做测试，但是理论上应该没有区别，你现在是遇到什么error？

**Comment by shoudeyunkaijianyueming** [comment]
有bug
错误
运行出错。请在启动Anki时按住「Shift」键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-12.6.4-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-07 19:49:37
相关插件：⁨Sync to Obsidian⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/shilei/Library/Application Support/Anki2/addons21/327710559/main.py", line 117, in sync
    sync_to_obsidian(browser)
  File "/Users/shilei/Library/Application Support/Anki2/addons21/327710559/main.py", line 44, in sync_to_obsidian
    obsidian_attachment_folder = json.load(
  File "json", line 293, in load
  File "encodings.ascii", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 304: ordinal not in range(128)

**Comment by JYC333** [comment]
我重新上传了一个版本，你可以试一下有没有解决你的问题

**Comment by shoudeyunkaijianyueming** [comment]
错误
运行出错。请在启动Anki时按住「Shift」键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.3.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-10 15:47:08
相关插件：⁨Sync to Obsidian⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/shilei/Library/Application Support/Anki2/addons21/327710559/main.py", line 128, in sync
    sync_to_obsidian(browser)
  File "/Users/shilei/Library/Application Support/Anki2/addons21/327710559/main.py", line 73, in sync_to_obsidian
    f.write(f"{note.tags[0]}")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-6: ordinal not in range(128)
还是不行，不知道原因

**Comment by shoudeyunkaijianyueming** [comment]
我虽然很喜欢note这个obsidian插件，但是有时出现显示同步成功，但实际并没有同步的问题，请问你能不能出个obsidian to anki从anki返回obsidian的插件呢，我认为obsidian to ankI 虽然配置麻烦点，但是同步很方便。
这是我使用的obsidian to anki 魔改版，我认为很好用
https://github.com/aviral-batra/Obsidian_to_Anki

**Comment by shoudeyunkaijianyueming** [comment]
对了这个在最新版本的obisidian中也不能用，我在reddit上找到了解决办法，修改了一处地方（具体我忘了），这是修改过的文件你替换就好(把zip去掉，就可以直接使用了）
[main.js.zip](https://github.com/JYC333/Anki-Sync-to-Obsidian/files/11190246/main.js.zip)

**Comment by JYC333** [comment]
我又更新了一下，可以再试试看，看起来应该是mac上的编解码跟win不太一样，新的bug已经是另一个地方了，希望没有其他地方了，手边没有mac测试是有些麻烦。

我暂时还是主要用note这个插件，短时间应该不会换到obsidian to anki，所以可能没有时间去做他的插件。如果之后note满足不了我的需求需要换到obsidian to anki的话，会考虑做一个相关的插件。

**Comment by shoudeyunkaijianyueming** [comment]
现在来看暂时没有问题了，但还是非常期待obsidian to anki的配套插件

**Comment by shoudeyunkaijianyueming** [comment]
谢谢老哥
