### ISSUE TITLE
Requires attachment folder to work

### ISSUE THREAD

**Issue by LeonStaufer** [JYC333/Anki-Sync-to-Obsidian#3]
The following exception occurs when trying to synchronize.

```
Caught exception:
Traceback (most recent call last):
  File "/Users/leon/Library/Application Support/Anki2/addons21/327710559/main.py", line 132, in sync
    sync_to_obsidian(browser)
  File "/Users/leon/Library/Application Support/Anki2/addons21/327710559/main.py", line 55, in sync_to_obsidian
    obsidian_attachment_folder = json.loads(
KeyError: 'attachmentFolderPath'
```

I believe this is because the plugin requires "attachmentFolderPath" to be set. https://github.com/JYC333/Anki-Sync-to-Obsidian/blob/99e896499f40aaed675d520e0424171c074d2319/main.py#L57

Perhaps it's possible to make attachment folder optional because notes do not necessarily contain media that needs to be copied. Instead, an error message could be displayed suggesting setting the attachment folder path.

Thank you for your work on the plugin, btw!

**Comment by LeonStaufer** [comment]
Or since the default location in Obsidian is just the vault folder, this could be used by the plugin as well.

**Comment by JYC333** [comment]
Sorry for the late update, now it should be fixed

**Comment by LeonStaufer** [comment]
Thank you :)
